import { icon } from './icons'
import type { AnalysisResult, AuditEvent, BatchResponse } from './types'

export function applicationTemplate() {
  return `<div class="ambient one"></div><div class="ambient two"></div>
  <header class="nav-shell"><div class="nav container"><a class="brand" href="#top"><b>${icon('mark')}</b><span class="brand-name">Morph<span>Guard</span></span><small>IMAGE INTEGRITY</small></a><nav aria-label="Page sections"><a class="active" href="#analyze" data-section="analyze">Analyze</a><a href="#how" data-section="how">How it works</a><a href="#privacy" data-section="privacy">Privacy</a></nav><span class="online" id="system-status"><i></i>Checking system</span></div></header>
  <main id="top"><section class="hero container"><div class="hero-copy"><p class="eyebrow">AI-POWERED IMAGE VERIFICATION</p><h1>See beyond the <em>surface.</em></h1><p class="lead">Detect face morphing with a high-performance forensic analysis pipeline built for clarity, speed, and confidence.</p><div class="actions"><a class="button" href="#analyze">Analyze an image ${icon('arrow')}</a><a href="#how">Explore the process ↓</a></div><p class="trust"><i></i><strong>Built on ResNet-50</strong> for robust visual feature analysis</p></div><div class="hero-art"><div class="scanner"><div class="portrait"><span class="corner a"></span><span class="corner b"></span><span class="corner c"></span><span class="corner d"></span><i></i></div><footer><span>● Face detected</span><span>98.7% match</span></footer></div><div class="chip secure">${icon('check')} Secure analysis</div><div class="chip layers"><b>02</b> Model layers<br><strong>2048 features</strong></div></div></section>
  <section class="metrics container"><div><strong>96.2%</strong><small>Test accuracy</small></div><div><strong>&lt; 10s</strong><small>Typical analysis</small></div><div><strong>2048</strong><small>Visual features</small></div><div><strong>7</strong><small>Pipeline modules</small></div></section>
  <section class="workspace container" id="analyze"><div class="heading"><div><p class="eyebrow">ANALYSIS WORKSPACE</p><h2>Upload. Analyze. Understand.</h2></div><p>Choose a single image for detailed screening or a set of images for a downloadable PDF report.</p></div><div class="mode-toggle"><button class="mode active" data-mode="single">Single image</button><button class="mode" data-mode="batch">Batch & report</button></div>
  <div id="single-workspace"><div class="panels"><section class="panel"><div class="panel-title"><h3><b>01</b>Select an image</h3><small>JPG · PNG · BMP</small></div><label id="single-dropzone" class="dropzone"><input id="single-file" type="file" accept="image/jpeg,image/png,image/bmp"><div id="single-empty">${icon('upload')}<strong>Drop your image here</strong><span>or click to browse from your device</span></div><div class="selected hidden" id="single-selected"></div></label><div class="meta"><span>Maximum file size: 10 MB</span><span>${icon('shield')} Private & secure</span></div><button id="single-analyze" class="button full" disabled>Start analysis ${icon('arrow')}</button></section><section class="panel"><div class="panel-title"><h3><b>02</b>Analysis result</h3><small id="single-badge">Awaiting image</small></div><div class="result-empty" id="single-empty-result">${icon('image')}<h4>Your result will appear here</h4><p>We will show the prediction, confidence, and a trace of the analysis workflow.</p></div><div class="result hidden" id="single-result"></div></section></div></div>
  <div id="batch-workspace" class="hidden"><section class="batch-panel panel"><div class="panel-title"><h3><b>01</b>Select batch images</h3><small>Up to 50 images</small></div><label id="batch-dropzone" class="dropzone batch-dropzone"><input id="batch-files" type="file" accept="image/jpeg,image/png,image/bmp" multiple><div>${icon('files')}<strong>Drop multiple images here</strong><span>Select two or more images to generate a comparison report</span></div></label><div id="batch-list" class="batch-list"><p>No images selected yet.</p></div><button id="batch-analyze" class="button full" disabled>Analyze batch & generate PDF ${icon('arrow')}</button></section><section class="panel batch-result"><div class="panel-title"><h3><b>02</b>Batch report</h3><small id="batch-badge">Awaiting files</small></div><div class="result-empty" id="batch-empty-result">${icon('files')}<h4>Your batch report will appear here</h4><p>Each image is independently analyzed. A PDF summary becomes available when processing completes.</p></div><div class="result hidden" id="batch-result"></div></section></div></section>
  <section class="process container" id="how"><p class="eyebrow">TRANSPARENT BY DESIGN</p><h2>How the analysis works</h2><div class="cards"><article><b>01</b>${icon('image')}<h3>Image validation</h3><p>Your file is checked for format, integrity, and quality before processing.</p></article><article><b>02</b><i class="star">✦</i><h3>Feature extraction</h3><p>ResNet-50 maps visual patterns into a detailed 2048-dimensional representation.</p></article><article><b>03</b>${icon('shield')}<h3>Risk assessment</h3><p>Our classifier evaluates the evidence and returns a clear, calibrated prediction.</p></article></div></section>
  <section class="privacy container" id="privacy"><b>${icon('shield')}</b><div><p class="eyebrow">PRIVACY FIRST</p><h2>Your images stay under your control.</h2><p>Each submission is processed for analysis only. The dashboard shows a model prediction, not a definitive forensic conclusion.</p></div><small>Encrypted<br>workflow</small></section></main>
  <footer class="footer container"><a class="brand" href="#top"><b>${icon('mark')}</b><span class="brand-name">Morph<span>Guard</span></span></a><span>AI-Based Image Morphing Detection System</span><span>© 2026 MorphGuard</span></footer><div id="toast" class="toast hidden"></div>`
}

export function analysisProgress() {
  return `<div class="analysis-progress"><i class="spinner big"></i><h4>Analyzing visual evidence</h4><p>The pipeline is processing your image through the following stages.</p><ol><li class="active"><b>1</b>Image validation and submission record</li><li><b>2</b>Face detection and landmark alignment</li><li><b>3</b>ResNet-50 feature extraction (2048 signals)</li><li><b>4</b>Classifier prediction and confidence scoring</li><li><b>5</b>Audit trail creation</li></ol></div>`
}

export function resultCard(result: AnalysisResult, events: AuditEvent[]) {
  const morph = result.predicted_label === 'Morphed'; const score = result.confidence_percentage.toFixed(1)
  return `<div class="verdict ${morph ? 'risk' : 'safe'}"><i>${morph ? '!' : icon('check')}</i><div><small>Model prediction</small><h4>${result.predicted_label}</h4><p>${morph ? 'Potential morphing indicators detected' : 'No strong morphing indicators detected'}</p></div><strong>${score}<small>%</small></strong></div><div class="confidence"><span>Confidence score <b>${score}%</b></span><i><em style="width:${score}%"></em></i></div><div class="probabilities"><span>Genuine <b>${(result.class_probabilities.Genuine * 100).toFixed(2)}%</b></span><span>Morphed <b>${(result.class_probabilities.Morphed * 100).toFixed(2)}%</b></span></div><div class="audit-summary"><strong>${icon('shield')} Workflow trace</strong><span>${events.length} audit events recorded · ${events.map(event => event.event_type.replace('_', ' ')).join(' → ') || 'record pending'}</span></div><p class="note">This is an AI screening result, not a definitive forensic conclusion.</p>`
}

export function batchCard(batch: BatchResponse, events: AuditEvent[], reportUrl: string) {
  const rows = batch.items.map(item => `<li><span>${item.succeeded ? '✓' : '!'}</span>${escapeHtml(item.filename)}<b>${item.succeeded ? item.result?.predicted_label ?? 'Processed' : 'Failed'}</b></li>`).join('')
  return `<div class="batch-summary"><div><span>Processed images</span><strong>${batch.successful_count + batch.failed_count}</strong></div><div><span>Successful</span><strong>${batch.successful_count}</strong></div><div><span>Needs review</span><strong>${batch.failed_count}</strong></div></div><ul class="batch-items">${rows}</ul><a class="button report-button" href="${reportUrl}" target="_blank" rel="noopener">Download PDF report ${icon('arrow')}</a><div class="audit-summary"><strong>${icon('shield')} Batch audit</strong><span>${events.length} audit events recorded for this batch.</span></div>`
}

export function escapeHtml(value: string) { const element = document.createElement('div'); element.textContent = value; return element.innerHTML }
